"""AI Features package: catalog, availability, and setup panel."""

from __future__ import annotations

from anonymizer.controller.ai.tseg.config import (
    default_installed_segmentation_mode,
    installed_segmentation_mode_menu_values,
    segmentation_mode_display,
    segmentation_mode_menu_values,
)
from anonymizer.view.ai.features.availability import (
    AiFeatureDownloadManager,
    DownloadCompleteEvent,
    any_ai_batch_feature_allowed,
    brain_structures_allowed,
    collapse_inventory_labels,
    face_blur_allowed,
    friendly_task_label,
    get_download_manager,
    harmonize_allowed,
    harmonize_allowed_for_modality,
    pixel_phi_allowed,
)
from anonymizer.view.ai.features.catalog import (
    AiFeatureId,
    AiFeatureSpec,
    AiModelGroupId,
    AiModelGroupSpec,
    all_download_ids,
    all_model_groups,
    download_id_for_weight_kind,
    feature_description,
    feature_spec,
    feature_title,
    group_by_download_id,
    groups_for,
    model_group_spec,
    top_level_features,
    weight_kind_for_download_id,
)
from anonymizer.view.ai.features.panel import AiFeaturesPanel

__all__ = [
    "AiFeatureDownloadManager",
    "AiFeatureId",
    "AiFeatureSpec",
    "AiFeaturesPanel",
    "AiModelGroupId",
    "AiModelGroupSpec",
    "DownloadCompleteEvent",
    "all_download_ids",
    "all_model_groups",
    "any_ai_batch_feature_allowed",
    "brain_structures_allowed",
    "collapse_inventory_labels",
    "default_installed_segmentation_mode",
    "download_id_for_weight_kind",
    "face_blur_allowed",
    "feature_description",
    "feature_spec",
    "feature_title",
    "friendly_task_label",
    "get_download_manager",
    "group_by_download_id",
    "groups_for",
    "harmonize_allowed",
    "harmonize_allowed_for_modality",
    "installed_segmentation_mode_menu_values",
    "model_group_spec",
    "pixel_phi_allowed",
    "segmentation_mode_display",
    "segmentation_mode_menu_values",
    "top_level_features",
    "weight_kind_for_download_id",
]
