"""Register Playbook harmonize label msgids for xgettext extraction."""

from anonymizer.utils.translate import _


def _register_playbook_label_msgids() -> None:
    # Body parts
    _("Whole body")
    _("Brain")
    _("Head")
    _("Pituitary")
    _("Temporal bone")
    _("Temporomandibular joint")
    _("Face")
    _("Orbit")
    _("Paranasal sinuses")
    _("Nasopharynx")
    _("Oropharynx")
    _("Larynx")
    _("Neck")
    _("Thyroid")
    _("Parathyroid")
    _("Chest")
    _("Chest abdomen pelvis")
    _("Mandible")
    _("Heart")
    _("Coronary arteries")
    _("Breast")
    _("Abdomen")
    _("Pelvis")
    _("Abdomen pelvis")
    _("Aorta")
    _("Liver")
    _("Kidney")
    _("Adrenal")
    _("Rectum")
    _("Uterus")
    _("Fetus")
    _("Prostate")
    _("Upper extremity")
    _("Shoulder")
    _("Elbow")
    _("Wrist")
    _("Hand")
    _("Finger")
    _("Lower extremity")
    _("Femur")
    _("Hip")
    _("Knee")
    _("Ankle")
    _("Foot")
    _("Joints")
    _("Spine")
    _("Cervical spine")
    _("Thoracic spine")
    _("Lumbar spine")
    _("Sacrum")
    _("Sacroiliac joints")
    _("Brain and face")
    _("Brain and neck")
    _("Brain, face, and cervical spine")
    _("Brain and cervical spine")
    _("Cervical and thoracic spine")
    _("Thoracic and lumbar spine")
    _("Entire spine")
    _("Small bowel through terminal ileum")
    _("Pancreas")
    # Planes
    _("Axial")
    _("Sagittal")
    _("Coronal")
    _("Axial oblique")
    _("Sagittal oblique")
    _("Coronal oblique")
    _("Oblique")
    # IV contrast
    _("Without contrast")
    _("With contrast")
    _("Early arterial")
    _("Late arterial")
    _("Portal venous")
    _("Arterial")
    _("Venous")
    _("Delayed")
    _("Pulmonary arterial")
    _("Nephrogenic")
    _("Cortomedullary")
    _("Equilibrium")
    _("Excretory")
    _("Dynamic")
    # Thickness / laterality / luminal / kernel / view
    _("Sub-millimeter (< 1 mm)")
    _("Thin (≥ 1 mm and < 2.5 mm)")
    _("Medium (≥ 2.5 mm and < 5 mm)")
    _("Thick (≥ 5 mm)")
    _("Left")
    _("Right")
    _("Bilateral")
    _("Oral contrast")
    _("Rectal contrast")
    _("Cystogram contrast")
    _("Post-void")
    _("Tube contrast")
    _("Intra-articular contrast")
    _("Intrathecal contrast")
    _("Bone kernel")
    _("Lung kernel")
    _("Prone")
    _("Left lateral decubitus")
    _("Right lateral decubitus")
    # Series type
    _("Exam localizer")
    _("Radiation dose sheet")
    _("Used for tracking the contrast bolus or heart rhythm")
    _("More than plane reformat; includes 3D lab outputs and AI outputs")
    _("Images saved by radiologists")
    _("PET/CT fusion and multi spectral energies fused together")
    _("Contrast dose sheet")
    _("Multiplanar reformat")
    _("Native")
    _("Doppler")
