"""Register Playbook harmonize label msgids for xgettext extraction."""

from anonymizer.utils.translate import _


def _register_playbook_label_msgids() -> None:
    _("Chest")
    _("Abdomen")
    _("Head")
    _("Brain")
    _("Chest abdomen pelvis")
    _("Axial")
    _("Sagittal")
    _("Coronal")
    _("Axial oblique")
    _("Sagittal oblique")
    _("Coronal oblique")
    _("Oblique")
    _("Without contrast")
    _("With contrast")
    _("Early arterial")
    _("Late arterial")
    _("Portal venous")
    _("Arterial")
    _("Venous")
    _("Delayed")
    _("Pulmonary arterial")
    _("Nephrogenic")
    _("Cortomedullary")
    _("Equilibrium")
    _("Excretory")
    _("Dynamic")
    _("Reconstruction (< 1 mm)")
    _("Thin ( 1 mm and < 2.5 mm)")
    _("Standard ( 2.5 mm and  5 mm)")
    _("Thick ( 5 mm)")
    _("Exam localizer")
    _("Radiation dose sheet")
    _("Used for tracking the contrast bolus or heart rhythm")
    _("More than plane reformat; includes 3D lab outputs and AI outputs")
    _("Images saved by radiologists")
    _("PET/CT fusion and multi spectral energies fused together")
    _("Contrast dose sheet")
    _("Multiplanar reformat")
    _("Native")
