TEST_LOCAL_SCP_IP = "127.0.0.1"
TEST_LOCAL_SCP_PORT = 1041
TEST_LOCAL_SCP_AET = "PYANON"

TEST_SCU_IP = "127.0.0.1"
TEST_SCU_AET = "SCU_AET"

TEST_PACS_IP = "127.0.0.1"
TEST_PACS_PORT = 1042
TEST_PACS_AET = "TESTPACS"
TEST_PACS_KNOWN_AET = {TEST_LOCAL_SCP_AET: (TEST_LOCAL_SCP_IP, TEST_LOCAL_SCP_PORT)}
