"""User ROI annotation store under ``0_TS_SEG/annotations/``."""

from __future__ import annotations

from anonymizer.controller.annotations.brush import (
    UNDO_LIMIT,
    begin_stroke_capture,
    commit_stroke_undo,
    stamp_brush,
    undo_last_stroke,
)
from anonymizer.controller.annotations.export_dicom_seg import export_dicom_seg
from anonymizer.controller.annotations.export_nii import export_ml_bundle
from anonymizer.controller.annotations.import_nii import (
    ImportProfile,
    ImportResult,
    detect_and_import,
    ensure_series_annotation_geometry,
    import_binary_masks,
    import_folder_binary_masks,
    import_label_nifti,
    parse_itk_snap_label_file,
    parse_nnunet_dataset_json,
)
from anonymizer.controller.annotations.store import (
    ANNOTATIONS_DIRNAME,
    EDITS_DIRNAME,
    LABEL_MAP_FILENAME,
    LABELS_FILENAME,
    AnnotateSession,
    LabelEntry,
    PaintTargetKind,
    StrokeUndo,
    add_user_label,
    annotations_dir,
    annotations_exist,
    edit_mask_path,
    edits_dir,
    ensure_ts_edit,
    label_map_path,
    labels_path,
    load_annotate_session,
    next_label_color,
    next_label_id,
    save_annotate_session,
)

__all__ = [
    "ANNOTATIONS_DIRNAME",
    "EDITS_DIRNAME",
    "LABEL_MAP_FILENAME",
    "LABELS_FILENAME",
    "UNDO_LIMIT",
    "AnnotateSession",
    "LabelEntry",
    "PaintTargetKind",
    "StrokeUndo",
    "add_user_label",
    "annotations_dir",
    "annotations_exist",
    "begin_stroke_capture",
    "commit_stroke_undo",
    "edit_mask_path",
    "edits_dir",
    "ensure_series_annotation_geometry",
    "ensure_ts_edit",
    "export_dicom_seg",
    "export_ml_bundle",
    "detect_and_import",
    "import_binary_masks",
    "import_folder_binary_masks",
    "import_label_nifti",
    "ImportProfile",
    "ImportResult",
    "label_map_path",
    "labels_path",
    "load_annotate_session",
    "next_label_color",
    "next_label_id",
    "parse_itk_snap_label_file",
    "parse_nnunet_dataset_json",
    "save_annotate_session",
    "stamp_brush",
    "undo_last_stroke",
]
